server:
  port: 8091
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbtest?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource



decorator:
  datasource:
    p6spy:
      custom-appender-class: com.p6spy.engine.spy.appender.Slf4JLogger
      log-format: com.yang.common.logging.CustomLogMessageFormat